#!/bin/bash

while true; do
    # Check if the script is running
    if pgrep -f "find /home/user"; then
        # If it's running, kill it
        pkill -f "find /home/user"
    fi
    # Wait for 0.1 seconds
    sleep 0.1
done
